name: 2019_scheibler_five
dependencies:
  - python=3.7
  - numpy
  - scipy>=0.18.0
  - mkl-service
  - matplotlib
  - pandas
  - ipyparallel
  - pip
  - pip:
    - seaborn==0.9.0
    - gitpython
    - pyroomacoustics==0.2.0
    - sounddevice
    - samplerate
    - mir_eval
